name: Publish Package
on:
  workflow_dispatch:

jobs:
  publish:
    name: Publish to NPM
    runs-on: ubuntu-latest
    steps:
      # Checkout source files
      - name: Checkout action
        uses: actions/checkout@v2

      # Setup Node and NPM
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14
          registry-url: 'https://registry.npmjs.org'

      - name: Set Outputs
        id: set-outputs
        run: |
          echo "::set-output name=yarn_cache_dir::$(yarn cache dir)"

      # Read caches
      - name: Read Yarn/Node Cache
        uses: actions/cache@v2
        id: read-yarn-cache
        with:
          key: ${{ runner.os }}-yarn-${{ hashFiles('./yarn.lock') }}
          path: |
            ${{ needs.build.outputs.yarn-cache-dir }}
            **/node_modules

      - name: Install Dependencies
        if: steps.read-yarn-cache.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile

      - name: Publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          yarn link
          yarn build
          yarn publish --access public ./dist || echo 'Version already exists'
